EsupPortail/pod

pod_project/core/utils.py
move scale properties in encoding mp4 function, UnboundLocalError: local variable 'scale' referenced before assignment
=> hotfix in encoding function

pod_project/pods/models.py
add pep8 compliant
add remove accent function to remove accent in tag
change all data in database with this :
import unicodedata
from taggit.models import Tag
lt = Tag.objects.all()
def remove_accents(input_str):
nkfd_form = unicodedata.normalize('NFKD', unicode(input_str))
return u"".join([c for c in nkfd_form if not unicodedata.combining(c)])
for t in lt:
t.name = remove_accents(t.name)
t.save()
=> fixbug with tag

pod_project/core/views.py, pod_project/pods/views.py
improve folder display speed by giving the id of the root folder of the user in session if not exists
=> add user root folder id in session if not exist

pod_project/pods/models.py
fix bug with enrich save integrity error.
=> use EnrichPods to get next id in save def and rename chapter choices in enrich choices

pod_project/core/static/JS/player.js
improve js function to change resolution.  remove 1080p and take the highest resolution available.
=> switch to ths highest resolution

pod_project/core/utils.py
don't delete this branch because the tests without webm encoder are still not functional
=> remove call directly to settings var in encode video

pod_project/core/theme/LILLE1/assets/css/pod.css, traduction/django.po
There's a lot of changes in the css file (my editor performed tabs to spaces changes) but the significant one is L179: changed « bottom » value to 35px (org. 6px).
I committed PO changes in my dev branch to stop having to commit it in every L10n branch i start. Maybe it's a bad idea that will cause conflicts… If it does (sorry), tell me, and i will merge all my branches into one, solve eventual conflicts, and make a pull request with the result :) !
=> Feature: video thumb user tools hides title

pod_project/core/management/commands/add_user.py
Takes site name, site url, help mail etc. from settings, and assumes .csv file is in utf8.
=> Feature: make add_user command more generic

pod_project/pods/templates/videos/video.html
Some users share their draft pods and ask why it doesn’t work…
=> Feature: draft pod cannot be shared.

pod_project/pods/templates/videos/video_edit.html, pod_project/pods/views.py, traduction/django.po
* Added messages about Draft / Restricted access / etc.
* All messages are now in separate Bootstrap panels.
* Some text improvements.
=> Feature: improving help in video edit template

pod_project/core/static/JS/video_edit.js, pod_project/pods/templates/videos/video_edit.html
=> Feature: uploaded percentage text added in video_edit progress bar

pod_project/pods/templates/search/search_video.html, pod_project/pods/templates/videos/videos_list.html, traduction/django.po
Separates icons for:
- password protected and authentication access restrictions,
- chaptered and enriched contents.
Also localizes icons links “title” attribute.
=> Feature: video protected / authentified access separate icons

pod_project/pods/templates/videos/video_edit.html, traduction/django.po
Fixes the upload limit message always in plural form in “video_edit” template.
=> Feature: adds upload limit message singular form

pod_project/core/utils.py, pod_project/pod_project/settings-sample.py
cf : 
https://trello.com/c/GgB0I2Zj
https://trello.com/c/1HhwGj32
=> put encoding commands in parameters

pod_project/pods/templates/channels/my_channels.html, traduction/django.po
Same problem than in django-filer i18n.
Before:
Now:
Same for null value.
=> Bugfix : my channels stats block i18n null / singular / plural.

pod_project/pods/models.py
Formatage de date_added pour le json à envoyer à elasticsearch, comme pour date_evt.
Il peut y avoir des erreurs sinon.
=> format date_added like date_evt in the json dump for es

pod_project/core/theme/LILLE1/assets/css/admin.css, pod_project/core/theme/LILLE1/less/includes/_admin.less, traduction/django.po
- Removes search icon double display for filer file field in admin pages ;
- removes unwanted comments from po file, introduced in previous filer_upgrade_fix branch (sorry!).
=> Bugfix: django filer upgrade fix 2

pod_project/core/templates/header.html, pod_project/core/theme/LILLE1/assets/css/pod.css, pod_project/core/theme/LILLE1/less/includes/_pod.less, pod_project/pod_project/settings-sample.py, pod_project/pods/admin.py, pod_project/pods/forms.py, pod_project/pods/templates/channels/channel_edit.html, traduction/django.po, traduction/djangojs.po
- Gives « djangojs.po » file the same charset as « django.po », and adds file header information;
- insures same capitalization for all languages in language selector;
- language selector lists its elements in the user native language;
- removes duplicate channels in video edit form;
- improves Themes sub-form in channel edition by owners;
- lists owners by first name / last name / id in Admin video page.
=> Feature: various improvements before release

pod_project/core/static/js/player.js, pod_project/pods/templates/videos/extraheadplayer.html, traduction/django.po
This allows a user watching an embedded videos to come seeing it directly on Pod.
=> Feature: player logo is now clickable.

pod_project/core/theme/LILLE1/assets/css/pod.css, pod_project/core/theme/LILLE1/less/includes/_pod.less, pod_project/core/theme/LILLE1/less/includes/_settings.less, pod_project/core/theme/LILLE1/less/settings.less, pod_project/pods/templates/channels/channel.html
- « Channel » and « Theme » headbands are now limited in height, so images not formatted as headbands will display as if they were;
- this height limit value is a LESS var added to « settings.less » files in Pod theme;
- « Theme » icon fits into « Theme » selection button.
=> Feature: improved channel headband display

pod_project/core/theme/LILLE1/assets/css/pod.css, pod_project/core/theme/LILLE1/less/includes/_pod.less, pod_project/pods/templates/videos/video_edit.html, traduction/django.po
- separates general info and form specific info,
- one help text per form field,
- links to contact form where accurate to improve user feedback.
=> Feature: collapsing video edit side info.

pod_project/pods/templates/videos/chapter/form_chapter.html, pod_project/pods/templates/videos/chapter/list_chapter.html, pod_project/pods/templates/videos/enrich/form_enrich.html, pod_project/pods/templates/videos/enrich/list_enrich.html, pod_project/pods/templates/videos/video_chapter.html, pod_project/pods/templates/videos/video_completion.html, pod_project/pods/templates/videos/video_enrich.html, traduction/django.po
- Removes unknown markup (video_completion L509, video_chapter L370, video_enrich L472),
- properly closes glyphicon SPANs (not like INPUT or IMG),
- removes extra or double spaces,
- adds spaces to Django template syntax,
- adds indentation.
Also clears L10N glitch (start time ≠ start of the video).
=> Bugfix: chaptering / completion / enrichment markup cleaning

pod_project/pods/management/commands/create_pod_index.py, pod_project/pods/management/commands/encode_video.py, pod_project/pods/management/commands/index_videos.py
- Fixes a « global name is not defined » error when an error occurs in pods ES indexing,
- sets all messages in english,
- spaces / PEP8
=> Bugfix: transporterror is not defined

pod_project/pods/tests/tests_views.py
petite correction des tests unitaires
=> fix unit tests of chapters and enrich

pod_project/pod_project/urls-sample.py, pod_project/pods/templates/videos/video.html
Before:
After:
\+ PEP8 changes.
=> Feature: improving video headband display

pod_project/core/theme/DEFAULT/assets/css/pod.css, pod_project/core/theme/DEFAULT/less/includes/_pod.less
CSS mods to lower space between page elements, and to remove top margin for first title in BS panels (BS panels are useful to make announcements on the homepage, through CKEditor).
Before:
After:
This branch also makes player error messages visible by specifying a z-index to vjs-error-display class.
=> Feature: more compact layout

pod_project/pods/templates/videos/video_completion.html, traduction/django.po
The client-side JS validation in captions / subtitles form is working now.
=> feature: fix subtitles client-side validation

pod_project/pods/templates/videos/video.html, pod_project/pods/views.py
=> Master do dev

pod_project/pod_project/settings_local-sample.py, pod_project/pods/models.py
* change the model to
* make it work
* raise a deprecation message if you use CELERY_TO_ENCODE
=> ENCODE_VIDEO method in settings

pod_project/pod_project/settings_local-sample.py
this is needed to be registered by celery
=> docfix: make the module available at startup time

pod_project/pods/management/commands/index_videos.py
Hi
We corrected an issue for elasticsearch indexation videos for drafted recording.
We hope you will accept this code.
Thanks
=> fix index_videos cmd when pod is draft

pod_project/core/templates/base.html, pod_project/pod_project/settings-sample.py, pod_project/pod_project/settings_local-sample.py, pod_project/pod_project/urls-sample.py, pod_project/pods/templates/videos/video.html, pod_project/pods/views.py
See https://oembed.com/
With new setting OEMBED :
add in video pages a link tag with type application/json+oembed and href to json representation of the URL video. https://oembed.com/#section4
add url oembed and buid the json representation of the URL video
oembed works also with private videos
=> New feature : Oembed

pod_project/pods/templates/videos/video.html
Regression introduced in commit "fix video embed code" (cac2356715f24a541675883d6bf8a510c55a8a2d)
=> fix regression in iframe integration size
