pod_project/pod_project/settings-sample.py

- remove 'django_cas_gateway.middleware.CASMiddleware' in settings sample to add it only if cas is used

fix cas in middleware

---

pod_project/core/templates/userProfile.html
pod_project/core/views.py
pod_project/pods/models.py
pod_project/pods/templates/channels/channel_edit.html
pod_project/pods/templates/mediacourses/mediacourses_add.html
pod_project/pods/templates/search/search.html
pod_project/pods/templates/videos/chapter/form_chapter.html
pod_project/pods/templates/videos/enrich/form_enrich.html
pod_project/pods/templates/videos/ownertools.html
pod_project/pods/templates/videos/video_chapter.html
pod_project/pods/templates/videos/video_edit.html
pod_project/pods/templates/videos/video_enrich.html
pod_project/pods/templates/videos/videos_list.html
pod_project/pods/views.py
traduction/django.po

• removed « fuzzy » from po file,
• same text for all « video action » menus,
• restoring « subtile » vs « subheading » (wrong trad. introduced in previous I18n/L10n request), 
• simplified forms error msgs,
• po file regeneration,
• other minor changes.

Feature: I18n L10n mods #2

---

pod_project/pods/admin.py

set extra=0 in pods:admin:tabularinline to remove empty form
Trello : [ADMIN] Édition des données d'une vidéo : les champs « Contributeurs » vides déclenchent un refus de validation (au niveau du nom).

fix bug in video admin page

---

pod_project/core/utils.py

Cela pouvait bloquer le processus d'encodage d'une vidéo quand le titre était trop long.
J'ai mis `video.id` plutôt que le `video.slug[:180]` parce que j'avais toujours, dans certains cas, une entrée qui manquait dans la table **easy_thumbnails_thumbnail**, et même si ça n'avait apparamment pas une grande importance, j'ai préféré la jouer safe (et ça m'a paru plus logique que de trouver une autre valeur arbitraire plus basse).
Tu me dis s'il y a un qqch qui ne convient pas (et désolé pour le retard) :-)

correction d'un bug dans le nommage des thumbnails

---

README.md

« share.jpg » file has been removed, only leaving .png one.

Fix broken pod logo link

---

pod_project/pods/templates/videos/video_edit.html

Try to help users better understanding how to manage the visibility of their contents by hiding / showing the “is_restricted” and “password” inputs according to the state of the “is_draft” checkbox in the video_edit template.

Feature: draft hides other access inputs in video edit template

---

pod_project/core/utils.py

Takes the R parameter into account (if available) as follows:
* portrait : R = 90°, R = 270°, R = -90°;
* landscape : R = 0°, R = 180°, R = -180°.
… and switches W & H if the video is in portrait mode.
This solves the stretching problem in thumbnails, overviews and resulting encoded files.
The test in get_scale() has been removed because the « in_w <= in_h » case has no use and leads to wrong dimensions (too big).

Feature: portrait mode rotations

---

pod_project/pods/tests/tests_views.py

Bonjour,
Ci-joint un petit correctif qui permet de refaire fonctionner les tests unitaires sous la version 1.4.1.
Il fallait rajouter les champs cursus et main_lang lors du post du formulaire et corriger la recherche par type.
J'ai renommé la branche comme demandé.
Par contre je ne connais pas encore assez bien l'application pour en faire beaucoup plus. Je pourrai m'y investir quand nous passerons en mode projet de notre côté, car actuellement je bosses sur d'autres projets.
Cordialement,
Morgan

correct unit tests for v1.4.1

---

pod_project/core/templates/admin/filer/folder/directory_listing.html
traduction/django.po

To correct this problem:
until my [django-filer PR](https://github.com/divio/django-filer/pull/554) is published in a new release, if you feel necessary to update Pod with this upcoming filer release.
Note:
I tried to upgrade django-filer to 0.9.11 (using a copy of the virtualenv folder and of the database to roll-back) before doing this to see if it could solve the problem, but it didn't.

Feature: correct singular / plural in admin filer folder title

---

pod_project/pod_project/settings-sample.py

This may allow template overriding by copying the needed template file in the “template” theme folder.

Feature: allow template overriding in theme

---

pod_project/pods/templates/videos/video_edit.html
pod_project/pods/views.py

Fixes the problem of the video_edit page referring to itself when form is submitted.
Changes the way the user choice is transmitted (one key with numeric values in $_POST).
Starts uploading before launching visual animations (form disappearing, etc.).

Bugfix: non working “back to previous page“ button in video add/edit.

---

pod_project/core/static/JS/navigation.js
pod_project/core/templates/base.html
pod_project/core/theme/LILLE1/assets/css/pod.css
pod_project/core/theme/LILLE1/less/includes/_pod.less
pod_project/pods/models.py
pod_project/pods/templates/channels/channel_edit.html
pod_project/pods/templates/videos/video.html
pod_project/pods/templates/videos/video_chapter.html
pod_project/pods/templates/videos/video_completion.html
pod_project/pods/templates/videos/video_edit.html
pod_project/pods/templates/videos/video_enrich.html
pod_project/pods/views.py
traduction/django.po

Gives to client-side generated alert boxes the same structure and behaviors than the Django-BootStrap ones:
- alert boxes dismiss (are generated on the fly then removed from markup after use),
- no more square buttons but a better visibility of the “close cross”,
- lighter and DRYer code with less event checking,
- various little fixes.
Needs a collectstatic, .po file replacement and .mo regeneration.

Feature: alert box relies more on bootstrap native behaviors

---

pod_project/core/models.py
pod_project/pods/models.py

En réfléchissant dans le train j'ai trouvé une manière plus élégante d'implémenter le correctif pour le bug de get_storage_path.
Plutôt que de tester la classe de l'instance dans get_storage_path, j'ai implémenté une propriété owner dans le modèle de EncodingPods.

get_storage_path bug : use a more elegant way

---

pod_project/core/templates/header.html
pod_project/core/theme/LILLE1/assets/css/pod.css
pod_project/core/theme/LILLE1/less/includes/_pod.less
pod_project/pod_project/settings-sample.py
pod_project/pods/admin.py
pod_project/pods/forms.py
pod_project/pods/migrations/0010_channel_owners.py
pod_project/pods/models.py
pod_project/pods/templates/channels/channel.html
pod_project/pods/templates/channels/channel_edit.html
pod_project/pods/templates/channels/channels_list.html
pod_project/pods/tests/tests_delete_video.py
pod_project/pods/tests/tests_models.py
pod_project/pods/tests/tests_views.py
pod_project/pods/views.py
traduction/django.po
traduction/djangojs.po

This branch also:
- allows a staff member (*) channel owner to add / remove channel users via the admin « filter_horizontal » widget;
- removes channel / theme headband edition for non-staff member channel owners;
- sets channel visibility setting hideable to owners via « settings.py »;
- add an « Owners column » to admin channel list page, with clickable username that shows the user edit page;
- lists channel users with their first name, last name and username (instead of username only) in admin channel list and owner edition pages;
- introduces a new « djangojs.po » file for dynamic JS L10N.
Previous owner data is preserved via the included migration file.
(*) Django Admin does not perform any dynamic javascript localization for non-staff users as they never reach the admin pages …

Feature: a channel can have multiple owners

---

pod_project/pod_project/settings-sample.py
pod_project/pods/templates/videos/video.html

- Adds « dc.language »;
- adds « dc.coverage » from settings;
- « dc.rights » is now taken from settings;
- removes L10N for « dc.contributor » role (which remains in english).
Remaining tags:
- « dc.format »;
- « dc.relation ».

Feature: dublin core reaches 12 tags

---

pod_project/core/admin.py
traduction/django.po

Adds new columns in admin user list:
-  last_login,
- is_active,
- is_superuser;
and makes « email » column clickable.

Feature: more info in admin user list

---

pod_project/core/templates/navbar.html
pod_project/pods/templates/owners/owners.html
pod_project/pods/templates/owners/owners_list.html
pod_project/pods/templates/videos/videos.html
traduction/django.po

This branch names people posting content « Users » in the front-end, as it is in the back-end.
This way, users posting content they do not own will not be called "owners", nor "authors".

Feature: users can be authors, owners, or simply people posting content.

---

pod_project/core/templates/navbar.html

**This one replaces #138, which doesn't have any content (sorry!).**
Navbar icons will stay on the same line.
_Before:_
_After:_

Fixes navbar icon display with Firefox (the good one…)

---

pod_project/pod_project/settings-sample.py
pod_project/pods/templates/owners/owners.html
pod_project/pods/templates/videos/video.html
pod_project/pods/templates/videos/video_edit.html
traduction/django.po

- Improves « Embed/Share » textarea label,
- fixes 2 errors in templates strings,
- removes « DEFAULT_LANGUAGE » from settings as it is now [taken from « MODELTRANSLATION_DEFAULT_LANGUAGE » by « django-modeltranslation »](http://pydoc.net/Python/django-modeltranslation/0.11/modeltranslation.settings/).

Feature: localization improvements and fixes for 1.5.1

---

pod_project/core/views.py
pod_project/pod_project/urls-sample.py
pod_project/pod_project/urls.py

Bonjour,
J'ai rajouté une simple page "status/" toute bête qui renvoie juste un code 200.
Dans notre architecture avec "load balancer", ça permet au "load balancer" de requêter cette url pour savoir si l'application django est up ou down. Vu que le load balancer requête toutes les 15 secondes, il vaut mieux éviter d'utiliser la page d’accueil (requêtes sql inutiles, transfert de données inutiles).
Ça pourra servir pour les universités qui vont adopter ce type d'architecture.
Morgan

add a status page for load balancer

---

pod_project/pods/templates/channels/channels_list.html
pod_project/pods/templates/disciplines/disciplines_list.html
pod_project/pods/templates/owners/owners_list.html
pod_project/pods/templates/types/types_list.html

As previously done in 1.5.0 for « Channels » and « Owners » (when another image than the default one is used).
Before:
After:

Feature: remove play icon in non video list templates

---

pod_project/pods/templates/channels/channels_list.html
pod_project/pods/templates/disciplines/disciplines_list.html
pod_project/pods/templates/owners/owners_list.html
pod_project/pods/templates/types/types_list.html

Channel / owners / types / disciplines list image do not behave as video thumbs due to a missing class on their parent A.
Before:
After:

Bugfix: list images overfilling their containers

---

pod_project/core/static/js/player.js
pod_project/pods/templates/videos/extraheadplayer.html
traduction/django.po

- Solves a bug introduced in [PR#133](https://github.com/EsupPortail/pod/pull/133): link needs a « target=_blank » attribute to work when content is embedded;
- the logo isn't a link anymore when the player is inside a Pod video page (not embedded).

Bugfix: player logo link reloads inside iframe

---

pod_project/core/theme/LILLE1/assets/css/pod.css
pod_project/core/theme/LILLE1/less/includes/_pod.less
pod_project/pods/templates/channels/channels_list.html
pod_project/pods/templates/disciplines/disciplines_list.html
pod_project/pods/templates/owners/owners_list.html
pod_project/pods/templates/search/search_video.html
pod_project/pods/templates/types/types_list.html
pod_project/pods/templates/videos/videos_list.html

Adds the pagination container to channels / disciplines / owners / types list templates to center the pagination links (as in videos list), and moves from id to class to use BS pager class.

Feature: pagination container in list templates

---

pod_project/pods/models.py
pod_project/pods/views.py

Fixes the « Please import get_current_site from django.contrib.sites.shortcuts. » RemovedInDjango19Warning.

Feature: « RemovedInDjango19Warning » fix (get_current_site import)

---

pod_project/pods/templates/channels/channels_list.html
pod_project/pods/templates/disciplines/disciplines_list.html

Adds « preview » missing CSS class to default headband IMG in « disciplines » and « channels » lists templates, so they display as « videos », « owners » and  « types » lists.
Before:
After:
(Default headband IMGs are the right ones)

Feature: missing class in object list headband

---

pod_project/pods/templates/videos/video_edit.html

This branch fixes a minor UI bug in the « video_edit » template, where the « today » link of the JS calendar is not localized for non-staff users.
Before:
After:
It also removes hardcoded « static » path for « admin_media_prefix », needed for displaying the calendar icon if STATIC_URL isn't set to default value.

Bugfix: calendar « today » link not localized

---

pod_project/pods/templates/videos/ownertools.html
pod_project/pods/templates/videos/videos_list.html

This branch replaces « video_list » owner tools markup by including the « ownertools » template, so non-staff users gets the « Add contributors » button instead of the staff-users one (paper-clip), and they are not told about subtitles and documents they cannot add.
Before:
After:
From now on, every toolbar change will take place in the « ownertools » template.

Feature: use ownertools in videos list

---

pod_project/core/templates/admin/base.html
pod_project/core/templates/fileBrowse.html
pod_project/core/templates/userProfile.html
pod_project/pod_project/urls-sample.py
pod_project/pods/templates/channels/channel_edit.html
pod_project/pods/templates/search/search_video.html
pod_project/pods/templates/videos/video_chapter.html
pod_project/pods/templates/videos/video_completion.html
pod_project/pods/templates/videos/video_edit.html
pod_project/pods/templates/videos/video_enrich.html

This branch modifies video templates by removing unused JS files calls and _admin_media_prefix_ declarations, using the « my-admin » route for JS catalog (instead of the _admin_ or _dynamic-media_ ones) and removing hardcoded « static » paths.
As a result, there are no more errors like this
in the JS console, and no more access denied
on I18N js catalog when the user is non-staff.

Feature: clear up javascript calls and declarations in video templates

---

pod_project/pod_project/settings-sample.py

Prevents Taggit from generating
> IntegrityError: (1062, "Duplicate entry 'gniiii' for key 'taggit_tag_name_4ed9aad194b72af1_uniq’ »)
which results in a 500 when associating existing tags spelled with uppercases or accented characters to videos.
https://github.com/alex/django-taggit/issues/9
https://github.com/alex/django-taggit/issues/308

Hotfix: tags are case and accent insensitive

---

pod_project/pods/templates/videos/video_completion.html
pod_project/pods/views.py
traduction/django.po

This branch stops validation of new enrichment / chapter / contributors/ subtitles and additional resources forms on creation, which results in field colorization and error message displaying before any user input.
**Before** (in the case of enrichment form)
**After**
It also corrects a typo in one error message.

Feature: new forms not invalidated on creation

---

pod_project/core/views.py

Email from « contact_us » form are currently sent to « settings.REPORT_VIDEO_MAIL_TO ».
These messages are now sent to « settings.HELP_MAIL » as intended by settings file.

Bugfix: contact us sends to report address

---

pod_project/core/theme/DEFAULT/assets/css/pod.css
pod_project/core/theme/DEFAULT/less/includes/_pod.less
pod_project/core/theme/DEFAULT/less/includes/_settings.less
pod_project/pods/models.py
pod_project/pods/templates/videos/completion/contributor/form_contributor.html
pod_project/pods/templates/videos/completion/download/form_download.html
pod_project/pods/templates/videos/completion/subtitle/form_subtitle.html
pod_project/pods/templates/videos/video_completion.html
traduction/django.po

This branch:
- prevents the use of “.srt” files as caption and subtitles files, as video.js has stopped using them after v4.11 ([more info here](https://github.com/videojs/video.js/issues/1956#issuecomment-85617607)),
- repairs the possibility to modify the subtitle / caption text size via LESS / CSS (broken by vjs 4.12).
> Note: existing caption or subtitles using “.srt” files will silently fail. Existing Pod instances using such files will have to replace them by “.vtt” files.

Feature: videojs upgrade mods

---

pod_project/pods/tests/tests_views.py

Since the check of input subtitles files (only .vtt) the previous tested file in Video_completion_TestView class are obsolete. Now the tested file have a correct .vtt extension.

Bugfix : update file tested in subtitle completion test

---

pod_project/pods/context_processors.py
pod_project/pods/models.py
pod_project/pods/templates/owners/owners_list.html
pod_project/pods/templates/videos/video.html
pod_project/pods/templatetags/list.py
pod_project/pods/tests/tests_models.py
pod_project/pods/views.py

Bonjour,
J'ai commencé l'optimisation des requêtes sql car nous rencontrons des problèmes de performance suite à la migration de nos contenus de audiovideocast sur pod.
En effet, la page "/videos" utilise 938 requêtes sql pour s'afficher !
Avec les modifications de cette pull request, on est passé à 83 requêtes sql.
En gros :
1) La navbar affiche les utilisateurs avec le nombre de leur cours entre parenthèse. Pour chaque utilisateur, une requête était exécutée pour récupérer ce nombre. Puisque nous avons environ 500 utilisateurs, il y a environ 500 requêtes qui était exécutées. L'utilisation du prefetch related sur l'élément OWNERS de templatetags/list.py a permis de réduire ce chiffre à 18. La navbar étant utilisée sur toutes les pages, les performance en sont fortement impactées. Le …

use prefetch related to improved requests

---

pod_project/pods/context_processors.py
pod_project/pods/tests/tests_models.py
pod_project/pods/tests/tests_views.py
pod_project/pods/views.py

Salut
On a détecté un bug avec les annotations Count. Elles comptaient le nombre d'encoding à la place du nombre de pod.
Du coup je les ai corrigé, le chiffre qui s'affiche est maintenant juste.
Pour ce faire, j'ai du filtrer les channels, disciplines, thèmes et types qui s'affichent sur la page d'accueil.
Comme pour les utilisateurs, seul les éléments qui contiennent au moins une vidéo non brouillon et avec un encoding s'afficheront. J'espère que ça vous convient.
Ça a également encore amélioré le temps de réponse.
J'ai adapté les tests unitaires.
Attend un peu avant de merge, je te confirmerai ça ici. L'équipe projet fait des tests cette après-midi sur ces correctifs.
Désolé pour le dérangement.
Merci

Unistra improve sql 2

---

pod_project/core/models.py
pod_project/pods/models.py
pod_project/pods/templatetags/list.py
pod_project/pods/views.py

Permet de présenter les contenus triés par « id » à l'intérieur de la même « date_added », pour obtenir un pseudo ordre chronologique des contenus créés le même jour, en correspondance avec la meta « ordering » du modèle.
Notre besoin étant juste l'obtention d'un ordre d'affichage reflétant celui de création dans un contexte de contenus pré-existants, l'alternative consistant à passer le champ « date_added » en DATETIME a été rapidement écartée…

Feature: content order on same day

---

pod_project/pod_project/settings_local-sample.py

Remplacement de « storage_engine » (dépréciée depuis MySQL 5.7.5) par « default_storage_engine » (introduite par MySQL 5.5.3).
https://code.djangoproject.com/ticket/26121
https://docs.djangoproject.com/en/1.8/ref/databases/#creating-your-tables
À noter que ce couple clé / valeur de DATABASES['default']['OPTIONS'] ne sert que lors de la création des tables, donc lors de l'installation et de mises à jour effectuant des créations de tables (voir second lien ci-dessus) :
> This sets the default storage engine upon connecting to the database. After your tables have been created, you should remove this option as it adds a query that is only needed during table creation to each database connection.
On peut donc le commenter en usage normal pour économiser quelques requêtes…

Settings upgrade

---

pod_project/pod_project/settings_local-sample.py
pod_project/pods/context_processors.py

Cette PR ajoute la possibilité de ne pas afficher les utilisateurs « non staff » dans la liste de propriétaires de contenu (« Utilisateurs ») de la barre de menu principale (1), ainsi que - tant qu'à faire - ceux ayant été désactivés (comptes locaux uniquement, l'authentification CAS impliquant l'activation du compte) (2).
À Nice nous avons beaucoup de productions étudiantes, les enseignants et personnels fournissant du contenu se trouvent noyés dans la masse. Activer cette option (1) nous permet :
- de mettre l'accent sur les enseignants et personnels de l'Université,
- d'éviter les menus déroulants « Utilisateurs » trop longs.
Au cas où cela intéresserait d'autres institutions utilisatrices de Pod.
> 1 : MENUBAR_SHOW_STAFF_OWNERS_ONLY
> 2 : MENUBAR_HIDE_INACTIVE_OWNERS

Feature: filtering owners in menubar
